name: automerge
on:
  push:
    branches: master

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
 
#     - uses: actions/checkout@v2
#      - name: Deploy source-code
 #       uses: appleboy/scp-action@master
 #       env:
 #         HOST: ${{ secrets.SSH_HOST }}
 #        USERNAME: ${{ secrets.SSH_USERNAME }}
  #        PORT: 22
   #       KEY: ${{ secrets.SSH_KEY }}
    #    with:
     #     source: "*"
          #target: "/path/in/your/server"
          # https://www.cloudbooklet.com/setup-ci-cd-workflow-with-github-actions/
